apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: shopping-app
type: Opaque
data:
  mongo-root-username: YWRtaW4=
  mongo-root-password: YWRtaW4=
  #mongo-root-password: YWRtaW5AIzEyMzQk
