---
apiVersion: v1
kind: Pod
metadata:
   namespace: default
   name: webpage-server
spec:
  containers:
    - name: webpage-server
      image: nginx:1.15
      imagePullPolicy: Always
      ports:
        - containerPort: 80
          name: "webpage-server"
      volumeMounts:
        - mountPath: "/var/www/html"
          name: nginx-storage       
  volumes:
    - name: nginx-storage
      persistentVolumeClaim:
        claimName: nginx-pvc    

